
ALTER TABLE merchants ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'active';
ALTER TABLE merchants ADD COLUMN IF NOT EXISTS reserve_balance DECIMAL(10,2) DEFAULT 0;
ALTER TABLE merchants ADD COLUMN IF NOT EXISTS address VARCHAR(255);
