
ALTER TABLE contracts 
ADD COLUMN IF NOT EXISTS down_payment DECIMAL(10, 2) NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS borrower_email TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS borrower_phone TEXT NOT NULL DEFAULT '';
